### ISSUE TITLE
Currency Reading

### ISSUE THREAD

**Issue by Aubynj** [ZencashOfficial/Sphere_by_Horizen#26] opened 2020-03-09 00:32 UTC
I don't know if it a bug or error, currency reading shows **0.00** for all currency. I think horizon devs need to check this

**Comment by bellionaire** [comment] 2020-03-09 09:31
I am also seeing this issue in both Sphere by Horizen for Mac and Linux version 1.2.4-beta. On Linux it is showing 0.00 and on Mac it is not refreshing / updating the currency value under Total Balance.

**Comment by cronicc** [comment] 2020-04-07 13:29
Fixed in v1.2.5-beta.

**Closed by cronicc** 2020-04-07 13:29 UTC

**Comment by nikynik** [comment] 2022-05-10 06:16
The problem isn't
![Immagine 2022-05-10 081529](https://user-images.githubusercontent.com/7658768/167560610-74fc0f4d-86d4-493a-9761-a418f3cad24b.jpg)
 solved for me. How i can solve?

**Comment by angievi** [comment] 2022-05-10 18:52
hi @nikynik , can you describe more in detail the issue you are experiencing please? 
Any steps that would help us reproduce it and also, what version of Sphere are you using?
Thanks!

**Comment by nikynik** [comment] 2022-05-10 19:10
in the wallet i see the zen amount but i don't have the countervalue see the screenshot

![Immagine 2022-05-10 210920](https://user-images.githubusercontent.com/7658768/167704123-80f6299a-079f-4018-be12-5e1a107270da.jpg)
