### ISSUE TITLE
Addtional T addresses not appearing on second instance of the Sphere wallet

### ISSUE THREAD

**Issue by MrClayPole** [ZencashOfficial/Sphere_by_Horizen#32] opened 2020-06-03 11:26 UTC
When running a second instance of the same sphere wallet new T-addresses are not picked up on another instance.

To recreate the issues

1. Create a new Sphere by Horizen wallet
2. Install Sphere by Horizen on another device
3. Restore the "seed words" to the second instance
4. Create new T-Address on one of the 2 devices
5. Send some Zen to the new t-address

It then fails to appear on the other device. This can be resolved by removing the sphere config and restoring the "seed word" on the device. The new address then appears without its label.

While the above works, it's very cumbersome. Is it possible for sphere to scan for additional T-address as part of a refresh or add an option to scan for?

**Comment by uanl979** [comment] 2020-06-05 02:29
Hi @MrClayPole 

What you are experiencing is an expected behaviour from the wallet.

Sphere wallet was not designed to handle more than one instance of the same wallet (same seed phrase) in other devices at the same time. Therefore the lack of an address sync functionality.

You can manually trigger an "address sync" by restoring the wallet. I do agree that that this process is cumbersome. Nevertheless, there is an alternative, but you need to have your addresses numbered the same way in both instances to keep track.  Let me give you an example. 

- You have on both instances 10 T addresses numbered from 1 to 10. Maintaining the same number of addresses in both instances will assure that whenever you create an additional address on either of the two instances, you can just sync up the other one by adding an address as well. Since the seed is the same, the seed chain will also be the same. Meaning that the same address will be "created" on both places.

We do not have currently in our roadmap to add an address sync functionality. Our immediate priority for Sphere is to add sidechains support. 

Let me know If I cleared your doubt.
Regards

**Comment by MrClayPole** [comment] 2020-06-06 17:34
Thanks for taking the time to reply. It would be a nice feature to have especially when you release your mobile wallet. For the time being, I'm going to test syncing the "~/.config/Sphere by Horizen" dir between my laptop and my desktop. I know this could run it to issues with partial sync's but I can manually manage this to ensure I only sync when the app is not running.

Are any other folder paths I need to be aware of while I'm testing.

**Comment by uanl979** [comment] 2020-06-09 11:04
You will need to be synching the wallet file located in the Horizen folder. 

- Please look at this article. https://horizenofficial.atlassian.net/wiki/spaces/ZEN/pages/716734513/Sphere+5.2+-+What+Are+The+File+Locations+For+Sphere

- This will be prone to wallet corruption when copying and replacing the wallet file with the most updated one, when doing this be sure Sphere is closed, IMO it is way more easier the way I mentioned before. It's up to you. As long as you have your seed phrase secured, you'll be safe.

Regards

**Comment by uanl979** [comment] 2020-06-13 18:28
Hi there we already added this feature request on our to do list. Do not forget that we offer support to our community 24/7 at our Helpdesk
[support.horizen.global/](https://support.horizen.global/)

There is no ETA for getting this feature implemented, but I'll keep you posted whenever we start to target to implement this feature.

I will be closing this issue, if you have any additional doubts or issues, please raise a ticket at our support system :)

Regards

**Closed by uanl979** 2020-06-13 18:28 UTC
